#!/bin/bash
	
PIDFILE=/var/run/libvirt4occi.pid

cd /usr/share/libvirt4occi/
if [ "$1" == "--daemon" ]; then
    java -jar libvirt4occi.libvirt-0.1.jar > /dev/null 2> /dev/null < /dev/null &
    echo -n $! > $PIDFILE
else
    java -jar libvirt4occi.libvirt-0.1.jar
fi